#
# Licensed under the GPL License. You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#
# THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
# PURPOSE.
#

version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jakarta.inject:jakarta.inject-api
    versions:
    - "< 2.0.1"
    - ">= 2.0.0.a"
  - dependency-name: net.trajano.wagon:wagon-git
    versions:
    - "< 2.0.5"
    - ">= 2.0.4.a"
  - dependency-name: org.apache.tomcat:tomcat-catalina
    versions:
    - "< 9.0.37"
    - ">= 9.0.13.a"
  - dependency-name: org.apache.tomcat:tomcat-coyote
    versions:
    - "< 9.0.37"
    - ">= 9.0.13.a"
  - dependency-name: org.apache.tomcat:tomcat-dbcp
    versions:
    - "< 9.0.37"
    - ">= 9.0.13.a"
  - dependency-name: org.apache.tomcat:tomcat-dbcp
    versions:
    - "< 9.0.37"
    - ">= 9.0.14.a"
  - dependency-name: org.apache.tomcat:tomcat-jasper
    versions:
    - "< 9.0.37"
    - ">= 9.0.13.a"
